export const ADD_MESSAGE = 'DIALOG/ADD_MESSAGE';
export const ADD_NEW_MESSAGE_TEXT = 'DIALOG/ADD_NEW_MESSAGE_TEXT';

export const ADD_POST = 'PROFILE/ADD_POST';
export const ADD_NEW_POST_TEXT = 'PROFILE/ADD_NEW_POST_TEXT';
export const SET_STATUS = 'SET_STATUS';
export const UPDATE_STATUS = 'PROFILE/UPDATE_STATUS';

export const SET_USER_PROFILE = 'USER/SET_USER_PROFILE';
export const FOLLOW = 'USERS/FOLLOW'
export const UNFOLLOW = 'USERS/UNFOLLOW'
export const SET_USERS = 'USERS/SET_USERS'
export const SET_CURRENT_PAGE = 'USERS/SET_CURRENT_PAGE'
export const SET_TOTAL_USERS = 'USERS/SET_TOTAL_USERS'
export const TOGGLE_IS_FETCHING = 'USERS/TOGGLE_IS_FETCHING'
export const TOGGLE_IS_FOLLOWING_PROGRESS = 'USERS/TOGGLE_IS_FOLLOWING_PROGRESS'
export const SET_USER_DATA = 'USERS/SET_USER_DATA';
